### ISSUE TITLE
proposing a new file structure for backend (under process folder)

### ISSUE THREAD

**Issue by ZimuHuo** [michaelmendoza/node-studio#112]
> core 
        - fft.py
        - coil.py (coil combination, coil sensitivity maps, g factor)
        - phantom.py (brain phantom, shepp_logan phantom, coil sensitivity simulation) 
        - simulator.py (bSSFP, multiband ...)
> 2d recon
        - grappa
        - sense
        - nufft
> DOSMA
        - t2 
        - segemantation 
        - registration 
>  3d recon 
>  T2 
>  T1 
> EPI
> SMS
> motion correction
....

**Comment by michaelmendoza** [comment]
Sounds like a good idea!

**Comment by michaelmendoza** [comment]
Thinking go starting with this:

```
    /process - contains node processes computation code
        /core - base node process i.e. fft, mask, stats
        /integration/dosma - dosma intergation
        /io - io nodes i.e. file, display
        /phantom - phantom for simulation code
        /quantiative_maps - quantiative maps for tissue properies i.e. T1, T2 
        /recon - MR image reconstruction code
        /simulation - MR simulation code
```
