### ISSUE TITLE
return mutliple values 

### ISSUE THREAD

**Issue by ZimuHuo** [michaelmendoza/node-studio#95]
In sense undersampling, two values are returned: masked k space data and the undersampling ratio(stored in a tuple). However, when these are passed to the senseRecon, the arrangement and order might change, which leads to unstable results. 

The expected inputs are : ([masked images, undersampling ratio R], [sensitivity maps]) 

"Sometimes" it will be ([masked images], [sensitivity maps, undersampling ratio R]). Note the R is stored with sensitivity maps, which is wrong.

**Comment by michaelmendoza** [comment]
Resolved by #170.
